import ToasterProvider from '@/providers/ToastProvider';
import './globals.css'
import { Inter } from 'next/font/google'
import Modal from '@/components/Modal';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Trello Clone',
  description: 'Generated by create next app and developed by Michael',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ `${ inter.className } bg-[#f5f6f8]` }>
        <ToasterProvider />
        <Modal />
        { children }
      </body>
    </html>
  )
}
